name: Reusable

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "13.0"
    watchOS: "6.0"
    tvOS: "13.0"
    macOS: "10.15"
  bundleIdPrefix: ch.christianseiler

############
# fileGroups
############

fileGroups:
  - config

############
# Configs
############

configs:
  Debug: debug
  Release: release
  Adhoc: release
  Beta: release

############
# Include
############

include:
  - path: xcodegen/project_ios.yml
    relativePaths: false
  - path: xcodegen/project_macos.yml
    relativePaths: false

